# Generated by Django 5.2.8 on 2025-11-30 06:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bucket', models.CharField(choices=[('reserve', 'Reserve'), ('liquid', 'Liquid')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matured', models.BooleanField(default=False)),
                ('matured_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('fee', 'Fee'), ('interest', 'Interest'), ('reserve_to_liquid', 'Reserve -> Liquid')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bucket', models.CharField(blank=True, choices=[('reserve', 'Reserve'), ('liquid', 'Liquid')], max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('related_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.depositbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='UserFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('liquid_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
